oc_projet_8/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from purbeurre.views import GeneralView

urlpatterns = [
    path('', GeneralView.index),
    path('purbeurre/', include('purbeurre.urls', namespace='purbeurre')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/',
                        include(debug_toolbar.urls)), ] + urlpatterns

purbeurre/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

app_name = "purbeurre"

# define url of purbeurre website
urlpatterns = [
    path('', views.GeneralView.index, name='index'),
    path('credits/', views.GeneralView.show_credits, name='credits'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^substitutes/'
            r'for_replace/(?P<bar_code>[\d]+)/$',
            views.GeneralView.get_substitutes,
            name='substitutes'),
    re_path(r'^create_link/(?P<sign>[-\w:]+)/'
            r'substitute_choice/(?P<substitute_bar_code>[\d]+)/$',
            views.GeneralView.create_substitute_link, name='create_link'),
    re_path(r'^product/(?P<_id>[\d]+)/$', views.GeneralView.show_product,
            name='show_product'),
    path('my_products/', views.GeneralView.show_user_link, name='my_products'),
    path('my_account/', views.GeneralView.profile, name='profile'),
]

purbeurre/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """add category model"""

    name = models.CharField(max_length=200, unique=True)
    searched_substitutes = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Store(models.Model):
    """add Store model"""

    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """add Ingredient model"""

    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    """add Brand model"""

    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """add Product model"""

    product_url = "https://fr.openfoodfacts.org/product/{}"

    name = models.CharField(max_length=255)
    generic_name = models.CharField(max_length=255, null=True, blank=True)
    nutrition_grades = models.CharField(max_length=1, null=True, blank=True)
    bar_code = models.CharField(max_length=20, unique=True)
    fat = models.CharField(max_length=5, null=True, blank=True)
    saturated_fat = models.CharField(max_length=5, null=True, blank=True)
    sugars = models.CharField(max_length=5, null=True, blank=True)
    salt = models.CharField(max_length=10, null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)

    brands = models.ManyToManyField(Brand)
    ingredients = models.ManyToManyField(Ingredient)
    stores = models.ManyToManyField(Store)
    categories = models.ManyToManyField(Category, through='ProductCategory')
    substitutes = models.ManyToManyField('self',
                                         through='ProductSubstituteProduct',
                                         through_fields=('from_product',
                                                         'to_product'),
                                         symmetrical=False)

    def get_openfoodfacts_url(self):
        return self.product_url.format(self.bar_code)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class ProductCategory(models.Model):
    """ add ProductCategory model """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    hierarchy = models.IntegerField(default=1)


class ProductSubstituteProduct(models.Model):
    """add ProductSubstituteProduct model"""

    from_product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                     related_name='from_product')
    to_product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                   related_name="to_product")
    users = models.ManyToManyField(User)

    class Meta:
        unique_together = (('from_product', 'to_product'),)

purbeurre/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .utils import get_words_from_sentence


class SearchForm(forms.Form):
    """
    define the search form for search product on openfoodfacts
    """
    search = forms.CharField(label="Recherche", max_length=255, required=True,
                             min_length=2)

    def clean_search(self):
        data = tuple(get_words_from_sentence(self.cleaned_data['search']))
        if not data:
            raise forms.ValidationError("Entrez une recherche valide.")

        return " ".join(data)


class CustomUserCreationForm(UserCreationForm):
    """add email field to the registration form"""

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'email')

purbeurre/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.core import signing
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .forms import SearchForm, CustomUserCreationForm
from purbeurre.managers.openfoodfacts import ApiManager
from purbeurre.managers.database import DatabaseManager
from .models import ProductSubstituteProduct, Product


class GeneralView:
    @staticmethod
    def index(request):
        """render index page"""

        if request.method == "POST":
            navbar_search_form = SearchForm(request.POST, prefix="navbar")
            head_search_form = SearchForm(request.POST, prefix="head")
            valid = False
            search_post = None
            if navbar_search_form.is_valid():
                valid = True
                search_post = navbar_search_form.cleaned_data['search']
                head_search_form = SearchForm(prefix="head")
            elif head_search_form.is_valid():
                valid = True
                search_post = head_search_form.cleaned_data['search']
                navbar_search_form = SearchForm(prefix="navbar")
            if valid:
                products = ApiManager.do_research(search_post)
                return render(request, 'purbeurre/search.html', {
                    'search': search_post,
                    'products': products,
                    'navbar_search_form': navbar_search_form,
                })
        else:
            navbar_search_form = SearchForm(prefix="navbar")
            head_search_form = SearchForm(prefix="head")

        context = {
            'navbar_search_form': navbar_search_form,
            'head_search_form': head_search_form
        }

        return render(request, 'purbeurre/index.html', context)

    @staticmethod
    def show_credits(request):
        """render credits page"""

        return render(request, 'purbeurre/mentions_legales.html')

    @staticmethod
    def get_substitutes(request, bar_code):
        """ render substitutes page """

        navbar_search_form = SearchForm(prefix="navbar")
        sign = None
        sign_context = {'product': bar_code}
        substitutes_from_bdd = False

        product = ApiManager.get_product(bar_code)

        substitutes = DatabaseManager.get_substitutes_from_api(product)

        if not substitutes:
            substitutes = ApiManager.get_substitutes(product)
            if substitutes:
                DatabaseManager.save_substitutes(
                    product['categories_hierarchy'][-1],
                    substitutes)
        else:
            substitutes_from_bdd = True

        if substitutes_from_bdd:
            sign_context['substitutes'] = list(
                substitute.bar_code for substitute in substitutes)
            sign = signing.dumps(sign_context)
        elif substitutes:
            sign_context['substitutes'] = list(
                substitute['code'] for substitute in substitutes)
            sign = signing.dumps(sign_context)

        return render(request, 'purbeurre/substitutes.html', {
            'product': product,
            'substitutes': substitutes,
            'navbar_search_form': navbar_search_form,
            'sign': sign
        })

    @staticmethod
    def show_product(request, _id):
        """ render show product """

        product = get_object_or_404(Product.objects.prefetch_related(
            'brands',
            'ingredients',
            'stores',
            'categories'),
            pk=_id)
        navbar_search_form = SearchForm(prefix="navbar")

        return render(request, 'purbeurre/show_product.html', {
            'product': product,
            'navbar_search_form': navbar_search_form,
        })

    @staticmethod
    @login_required
    def create_substitute_link(request, sign, substitute_bar_code):
        """ render the creating link beetween product """

        try:
            _dict = signing.loads(sign)
        except signing.BadSignature:
            raise Exception('Altération détectée !')

        if substitute_bar_code not in _dict['substitutes']:
            raise Exception('Mauvaise requête !')

        do_save = True
        do_save_p_s_p = True
        urllib_product = True
        urllib_substitute = True
        product, substitute = None, None

        try:
            product = Product.objects.get(bar_code=_dict['product'])
            urllib_product = False
        except Product.DoesNotExist:
            pass

        try:
            substitute = Product.objects.get(bar_code=substitute_bar_code)
            urllib_substitute = False
        except Product.DoesNotExist:
            pass

        if not urllib_product and not urllib_substitute:
            do_save = False

            p_s_p_db = ProductSubstituteProduct.objects.filter(
                users=request.user,
                from_product=product,
                to_product=substitute
            )

            if p_s_p_db.exists():
                do_save_p_s_p = False
                messages.success(request, 'Substitut déjà sauvergardé'
                                          ' pour ce produit !')

        if do_save or do_save_p_s_p:
            if do_save:
                if urllib_product:
                    product = ApiManager.get_product(_dict['product'])
                    if not product:
                        raise Exception('Produit non existant.')
                if urllib_substitute:
                    substitute = ApiManager.get_product(substitute_bar_code)
                    if not substitute:
                        raise Exception('Substitut non existant.')

                if (urllib_product and not urllib_substitute) or \
                        (not urllib_product and urllib_substitute):
                    if urllib_product and not urllib_substitute:
                        product = DatabaseManager.save_product(product)
                    else:
                        substitute = DatabaseManager.save_product(substitute)

                    DatabaseManager.save_link_p_s_p(request.user, product,
                                                    substitute)
                else:
                    DatabaseManager.save_product(product,
                                                 substitutes=(substitute,),
                                                 user=request.user)
            else:
                DatabaseManager.save_link_p_s_p(request.user, product,
                                                substitute)

            messages.success(request, 'Substitut sauvegardé !')

        navbar_search_form = SearchForm(prefix="navbar")

        return render(request, 'purbeurre/create_substitute_link.html', {
            'product': product,
            'substitute': substitute,
            'navbar_search_form': navbar_search_form
        })

    @staticmethod
    @login_required
    def show_user_link(request):
        """ render user link beetween openfoodfacts products """

        user_products = Product.objects.filter(
            from_product__users=request.user) \
            .prefetch_related('substitutes',
                              'substitutes__categories',
                              'substitutes__brands',
                              'substitutes__stores',
                              'substitutes__ingredients',
                              'brands',
                              'ingredients',
                              'stores',
                              'categories').distinct()

        paginator = Paginator(user_products, 4)

        page = request.GET.get('page')
        try:
            paginator = paginator.page(page)
        except PageNotAnInteger:
            paginator = paginator.page(1)
        except EmptyPage:
            paginator = paginator.page(paginator.num_pages)

        navbar_search_form = SearchForm(prefix="navbar")

        return render(request, 'purbeurre/show_user_link.html', {
            'liste': paginator,
            'navbar_search_form': navbar_search_form
        })

    @staticmethod
    @login_required
    def profile(request):
        """ render profile page """

        navbar_search_form = SearchForm(prefix="navbar")
        return render(request, 'purbeurre/profile.html', {
            'navbar_search_form': navbar_search_form
        })


class SignupView(CreateView):
    """ render signup page """

    form_class = CustomUserCreationForm
    success_url = '/'
    model = User

    def get_success_url(self):
        messages.success(self.request, 'Création de compte réussie !')
        return super(SignupView, self).get_success_url()


class CustomLoginView(SuccessMessageMixin, LoginView):
    """ render login page """

    success_message = "Vous êtes connecté !"
    redirect_authenticated_user = True

purbeurre/templates/purbeurre/base.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" type="image/png"
          href="{% static 'purbeurre/img/flavicon.png' %}"/>

    <title>Pur beurre</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'purbeurre/vendor/bootstrap/css/bootstrap.min.css' %}"
          rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'purbeurre/vendor/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic'
          rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'purbeurre/vendor/magnific-popup/magnific-popup.css' %}"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'purbeurre/css/creative.min.css' %}" rel="stylesheet">
    <link href="{% static 'purbeurre/css/custom.css' %}" rel="stylesheet">

</head>

<body id="page-top">

{% if messages %}
    {% for message in messages %}
        <div class="toast" data-autohide="false" style="position: absolute;">
            <div class="toast-header">
                <strong class="mr-auto text-primary">Information</strong>
                <button type="button" class="ml-2 mb-1 close"
                        data-dismiss="toast">
                    &times;
                </button>
            </div>
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">

        <a class="navbar-brand js-scroll-trigger"
           href="{% url 'purbeurre:index' %}">
            <img id="logo" src="{% static 'purbeurre/img/logo.png' %}"
                 alt="pure_beurre_logo">
            Pur beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button"
                data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger"
                           data-target="#loggout"
                           href="{% url 'purbeurre:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'purbeurre:profile' %}"
                           data-target="#user"><i
                                class="fas fa-user"></i></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'purbeurre:my_products' %}"
                           data-target="#carrot" class="nav-link">
                            <i class="fas fa-carrot"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger"
                           data-target="#login"
                           href="{% url 'purbeurre:login' %}">
                            <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger"
                           data-target="#signup"
                           href="{% url 'purbeurre:signup' %}">
                            <i class="fas fa-user-plus"></i>
                        </a>
                    </li>
                {% endif %}
                {% block nav_right %}
                {% endblock %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                </li>
            </ul>
            {% if navbar_search_form %}
                <form class="form-inline my-2 my-lg-0" method="post"
                      action="{% url 'purbeurre:index' %}">
                    {% csrf_token %}
                    {{ navbar_search_form.search|add_class:"form-control mr-sm-2"|attr:"autocomplete:off" }}
                    <button class="btn btn-primary my-2 my-sm-0"
                            type="submit">Chercher
                    </button>
                </form>
            {% endif %}
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<section id="contact" class="background_color_rooibos_chocolat text-white">
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto text-center">
                <h2 class="section-heading">Contactez-nous !</h2>
                <hr class="my-4">
                <p class="mb-5">Vous avez trouvé une erreur sur le site ? Il
                    y a
                    un problème avec un produit ? N'hésitez pas à nous
                    contacter.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 ml-auto text-center">
                <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
                <p>123-456-6789</p>
            </div>
            <div class="col-md-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
                <p>
                    <a href="mailto:retours@purbeurre.com">retours@purbeurre.com</a>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="background_color_moules text-white">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fas fa-4x fa-gem text-primary mb-3 sr-icon-1"></i>
                    <h3 class="mb-3"><a href="{% url 'purbeurre:credits' %}">Mentions
                        légales</a></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
                    <h3 class="mb-3">
                        <a class="js-scroll-trigger"
                           href="#contact">Contact</a>
                    </h3>
                    <p class="mb-0">Nous serons heureux d'échanger
                        avec vous !</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
                    <h3 class="mb-3"><a
                            href="https://github.com/ivan-fr/oc_projet_8"
                            target="_blank">Code source</a></h3>
                    <p class="mb-0">Pour les développeurs, les
                        correcteurs et les curieux !</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'purbeurre/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'purbeurre/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'purbeurre/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'purbeurre/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
<script src="{% static 'purbeurre/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'purbeurre/js/creative.min.js' %}"></script>
<script>
    $(document).ready(function () {
        _height = $('nav').outerHeight();
        toasts = $('.toast');
        toasts.css({top: (_height + 10).toString() + 'px', 'left': '20px'});
        toasts.toast('show');
    });
</script>
</body>

</html>

purbeurre/templates/purbeurre/profile.html
{% extends 'purbeurre/base.html' %}

{% block content %}
    <header class="masthead text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-8 mx-auto background_color_moules p-3">
                    <h5 class="text-uppercase">Bonjour ! </h5>
                    <hr>
                    <h4>Votre nom d'utilisateur :
                        <strong>{{ user.username }}</strong></h4>
                    <hr>
                    <h4> Votre mail : <strong>{{ user.email }}</strong></h4>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

purbeurre/templates/purbeurre/search.html
{% extends 'purbeurre/base.html' %}
{% load static %}

{% block nav_right %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#products">Produits</a>
    </li>
{% endblock %}

{% block content %}
    <header class="smallheader text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="background_color_moules text-uppercase">
                        Résultats de recherche pour "{{ search }}"
                    </h1>
                </div>
            </div>
        </div>
    </header>

    <section id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-auto mx-auto">
                    {% if products %}
                        <h3>Choisissez le produit pour lequel vous voulez un
                            substituant :</h3>
                    {% else %}
                        <h3>Il n'y a pas de résultat pour la recherche.</h3>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                    <div class="col-md-4 col-sm-6 col-12 text-center">
                        <a href="{% url 'purbeurre:substitutes' product.code %}">
                            <div class="item">
                                {% if product.nutrition_grades %}
                                    <span class="notify-badge">{{ product.nutrition_grades|upper }}</span>
                                {% endif %}
                                {% if product.image_url %}
                                    <img src="{{ product.image_url }}"
                                         alt="aliment" height="200px"
                                         width="200px">
                                {% else %}
                                    <img src="{% static 'purbeurre/img/unknow.png' %}"
                                         alt="aliment" height="200px"
                                         width="200px">
                                {% endif %}
                                <div class="carousel-caption d-none d-md-block">
                                    <p>
                                        {% if product.product_name_fr %}
                                            {{ product.product_name_fr }}
                                        {% else %}
                                            {{ product.product_name }}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

purbeurre/templates/purbeurre/substitutes.html
{% extends 'purbeurre/base.html' %}
{% load static %}

{% block nav_right %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#substituts">Substituts</a>
    </li>
{% endblock %}

{% block content %}
    <header class="smallheader text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="item">
                        {% if product.nutrition_grades %}
                            <span class="notify-badge">{{ product.nutrition_grades|upper }}</span>
                        {% endif %}
                        <img src="{{ product.image_url }}"
                             alt="aliment" height="300px" width="300px">
                        <div class="carousel-caption d-none d-md-block">
                            <p>{{ product.product_name_fr }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="substituts">
        <div class="container">
            <div class="row">
                <div class="col-lg-auto mx-auto">
                    {% if substitutes %}
                        <h3>Vous pouvez remplacer ce produit par :</h3>
                    {% else %}
                        <h3>Il n'y a pas de substituts de meilleure qualité pour
                            ce produit.</h3>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% for product in substitutes %}
                    <div class="col-md-4 col-sm-6 col-12">
                        <div class="card mx-auto text-center mt-4"
                             style="width: 200px">
                            <div class="item item-in-card">
                                {% if product.nutrition_grades %}
                                    <span class="notify-badge">{{ product.nutrition_grades|upper }}</span>
                                {% endif %}
                                {% if product.image_url %}
                                    <img class="card-img-top"
                                         src="{{ product.image_url }}"
                                         alt="aliment" height="200px"
                                         width="200px">
                                {% else %}
                                    <img class="card-img-top"
                                         src="{% static 'purbeurre/img/unknow.png' %}"
                                         alt="aliment" height="200px"
                                         width="200px">
                                {% endif %}
                                <div class="carousel-caption d-none d-md-block">
                                    <p>{{ product.product_name_fr }}</p>
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="card-text"><a
                                        {% if product.code %}
                                            href="{% url 'purbeurre:create_link' sign product.code %}"
                                        {% else %}
                                            href="{% url 'purbeurre:create_link' sign product.bar_code %}"
                                        {% endif %}
                                >Sauvergader</a>

                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </section>
{% endblock %}